name: CI
on: [push, pull_request]
jobs:
  web:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0 # skip git hooks in CI
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable corepack & install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v
          node -v
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint --max-warnings=0
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Tests (if present)
        run: pnpm test --if-present
