name: CI
on: [push, pull_request]
jobs:
  web:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0 # skip git hooks in CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-
      - name: Verify toolchain
        run: |
          echo "PATH=$PATH"
          command -v node && node -v
          command -v pnpm && pnpm -v
          echo "pnpm store path: $(pnpm store path)"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint --max-warnings=0
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Tests (if present)
        run: pnpm test --if-present
